### ISSUE TITLE
Responsive Shopping Cart

### ISSUE THREAD

**Issue by ohnno** [ohnno/Brosa#44]
Location: Top Navigation
Browser: Mobile Safari
OS: iOS 8
Screen: Mobile

The current shopping cart does not seem to be responsive yet (text squished up).

**Comment by limcolin** [comment]
some admin needed

**Comment by limcolin** [comment]
fonts should be responsive. Product titles might look squished now, but that's because they are displaying twice (e.g. Audrey 2 x Dining Chair - Baptiste Grey - Audrey 2 x Dining Chair - Baptiste Grey).
That should look less squished when admin is done to fix product names. If not, it can be simply fixed.
